model:
  seed: 0
  load_model: ./src/model.pth  # XU None
#  load_model: None
  load_only_state_dict: False
  batch_size: 4
  optimizer: adam # sgd_mom, adam
  epochs: 100  # XU 100
  loss: gdice # ce, dice, gdice, focal
  learning_rate: 0.0001
  lr_decay_after_epoch: 40
  lr_decay_param: 0.1
  backbone: unet # unet, unetpp, deeplabv3p, pspnet, linknet
  encoder:
    backbone: resnet34
    weights: imagenet # imagenet or None
  decoder:
    activation: softmax # softmax or None
  method: pionono # supervised, prob_unet, conf_matrix, pionono
  pionono_config:
    mc_samples: 5
    no_head_layers: 3
    kl_factor: 0.0005
    reg_factor: 0.00001
    latent_dim: 8
    gold_annotators:
      - 0
    always_goldpred: False
    z_learning_rate: 0.02
    z_prior_sigma: 2.0
    z_posterior_init_sigma: 8.0
  prob_unet_config:
    original_backbone: False # use original prob-unet backbone (overwrites above configuration of backbone)
    kl_factor: 1.0
    reg_factor: 0.00001
    latent_dim: 6
  conf_matrix_config:
    level: global # 'global', 'pixel'
    min_trace: False # Switch if minimizing or maximizing trace of conf matrix
    activate_min_trace_epoch: 1 # epoch of activating trace minimization, before maximize, -1 to deactivate
    cmlayer_learning_rate: 0.01
    alpha: 1.0

logging:
  interval: 10
  artifact_interval: 9999 # steps of artifact (e.g. visualization) logging (in number of epochs)
  mlruns_folder: /work/work_arne/mlflow_server # http://127.0.0.1:5002
  tags:
    stage: initial
    spec: default