data:
  dataset_name: gleason19_crowdsourcing
  image_resolution: 1024
  class_no: 5
  class_names: ['NC', 'GG3', 'GG4', 'GG5', 'other']
  class_weights: [1., 1., 1., 1., 1.] # [2.69672952, 1.13585435, 0.78206914, 25.60014031, 0.41134248]
  ignore_last_class: False # set True if last class will be ignored during training and testing
  ignore_last_class_only_for_testing: True # set True if last class will be ignored during  testing
  path: /content/drive/Othercomputers/Mac/Google_Drive/dataset/Gleason19/resized_dataset/
  train:
    images: []
    masks: [ ]
  val:
    images: []
    masks: [ ]
  test:
    images: Train_imgs
    masks: []
  repeat_train_images: []
  repeat_factor: 2
  visualize_images:
    train: []
    val: []
    test:
      - 'slide002_core074.png'
      - 'slide005_core093.png'
      - 'slide005_core087.png'
      - 'slide006_core023.png'
      - 'slide001_core007.png'
      - 'slide005_core118.png'
      - 'slide007_core070.png'
      - 'slide005_core131.png'
      - 'slide006_core142.png'
      - 'slide001_core006.png'
      - 'slide001_core012.png'
      - 'slide005_core092.png'
      - 'slide005_core045.png'
      - 'slide005_core051.png'
      - 'slide005_core090.png'
      - 'slide001_core038.png'
      - 'slide001_core004.png'
      - 'slide001_core010.png'
      - 'slide003_core031.png'
      - 'slide005_core133.png'
      - 'slide005_core127.png'
      - 'slide002_core116.png'
      - 'slide005_core132.png'
      - 'slide001_core159.png'
      - 'slide006_core155.png'
      - 'slide006_core141.png'
      - 'slide001_core011.png'
      - 'slide001_core005.png'
      - 'slide001_core039.png'
      - 'slide005_core091.png'
      - 'slide002_core062.png'
      - 'slide007_core107.png'
      - 'slide005_core046.png'
      - 'slide002_core099.png'
      - 'slide002_core072.png'
      - 'slide006_core019.png'
      - 'slide005_core122.png'
      - 'slide001_core160.png'
      - 'slide001_core014.png'
      - 'slide002_core067.png'
      - 'slide002_core073.png'
      - 'slide005_core094.png'
      - 'slide005_core057.png'
      - 'slide005_core041.png'
      - 'slide005_core069.png'
      - 'slide002_core071.png'
      - 'slide003_core023.png'
      - 'slide003_core037.png'
      - 'slide007_core048.png'
      - 'slide002_core139.png'
      - 'slide001_core003.png'
      - 'slide005_core097.png'
      - 'slide005_core033.png'
      - 'slide002_core017.png'
      - 'slide006_core083.png'
      - 'slide001_core070.png'
      - 'slide003_core125.png'
      - 'slide006_core120.png'
      - 'slide006_core108.png'
      - 'slide003_core092.png'
      - 'slide003_core045.png'
      - 'slide001_core110.png'
      - 'slide005_core147.png'
      - 'slide007_core006.png'
      - 'slide007_core013.png'
      - 'slide001_core111.png'
      - 'slide003_core044.png'
      - 'slide006_core109.png'
      - 'slide001_core065.png'
      - 'slide001_core059.png'
      - 'slide006_core082.png'
      - 'slide002_core002.png'
      - 'slide005_core018.png'
      - 'slide001_core098.png'
      - 'slide001_core067.png'
      - 'slide003_core046.png'
      - 'slide007_core005.png'
      - 'slide007_core038.png'
      - 'slide001_core112.png'
      - 'slide006_core136.png'
      - 'slide003_core133.png'
      - 'slide001_core066.png'
      - 'slide005_core021.png'
      - 'slide005_core035.png'
      - 'slide005_core009.png'
      - 'slide002_core039.png'
      - 'slide006_core046.png'
      - 'slide003_core080.png'
      - 'slide007_core014.png'
      - 'slide007_core028.png'
      - 'slide005_core140.png'
      - 'slide005_core154.png'
      - 'slide007_core015.png'
      - 'slide003_core056.png'
      - 'slide003_core095.png'
      - 'slide006_core084.png'
      - 'slide006_core090.png'
      - 'slide003_core136.png'
      - 'slide001_core077.png'
      - 'slide003_core122.png'
      - 'slide006_core047.png'
      - 'slide002_core010.png'
      - 'slide007_core149.png'
      - 'slide005_core034.png'
      - 'slide002_core012.png'
      - 'slide003_core134.png'
      - 'slide006_core086.png'
      - 'slide003_core108.png'
      - 'slide001_core049.png'
      - 'slide003_core083.png'
      - 'slide003_core097.png'
      - 'slide006_core125.png'
      - 'slide003_core054.png'
      - 'slide003_core068.png'
      - 'slide007_core016.png'
      - 'slide007_core002.png'
      - 'slide003_core069.png'
      - 'slide003_core055.png'
      - 'slide006_core130.png'
      - 'slide003_core096.png'
      - 'slide006_core093.png'
      - 'slide006_core087.png'
      - 'slide003_core135.png'
      - 'slide006_core044.png'
      - 'slide006_core078.png'
      - 'slide005_core012.png'
      - 'slide001_core086.png'
      - 'slide001_core079.png'
      - 'slide001_core045.png'
      - 'slide006_core115.png'
      - 'slide006_core101.png'
      - 'slide006_core129.png'
      - 'slide007_core033.png'
      - 'slide002_core143.png'
      - 'slide003_core065.png'
      - 'slide006_core100.png'
      - 'slide006_core114.png'
      - 'slide006_core048.png'
      - 'slide007_core146.png'
      - 'slide007_core150.png'
      - 'slide002_core009.png'
      - 'slide001_core046.png'
      - 'slide006_core089.png'
      - 'slide003_core107.png'
      - 'slide006_core102.png'
      - 'slide006_core116.png'
      - 'slide003_core098.png'
      - 'slide003_core067.png'
      - 'slide005_core159.png'
      - 'slide007_core024.png'
      - 'slide002_core140.png'
      - 'slide007_core031.png'
      - 'slide006_core088.png'
      - 'slide006_core077.png'
      - 'slide005_core038.png'
      - 'slide002_core030.png'
      - 'slide006_core098.png'
      - 'slide006_core113.png'
      - 'slide002_core144.png'
      - 'slide002_core150.png'
      - 'slide002_core145.png'
      - 'slide007_core008.png'
      - 'slide003_core077.png'
      - 'slide003_core117.png'
      - 'slide006_core066.png'
      - 'slide001_core095.png'
      - 'slide002_core025.png'
      - 'slide005_core029.png'
      - 'slide005_core017.png'
      - 'slide002_core033.png'
      - 'slide006_core058.png'
      - 'slide001_core083.png'
      - 'slide001_core040.png'
      - 'slide003_core129.png'
      - 'slide006_core110.png'
      - 'slide001_core134.png'
      - 'slide003_core075.png'
      - 'slide001_core109.png'
      - 'slide006_core105.png'
      - 'slide001_core069.png'
      - 'slide001_core041.png'
      - 'slide001_core055.png'
      - 'slide003_core114.png'
      - 'slide006_core071.png'
      - 'slide002_core026.png'
      - 'slide002_core082.png'
      - 'slide002_core096.png'
      - 'slide002_core041.png'
      - 'slide002_core055.png'
      - 'slide006_core016.png'
      - 'slide001_core146.png'
      - 'slide007_core078.png'
      - 'slide007_core044.png'
      - 'slide005_core111.png'
      - 'slide007_core093.png'
      - 'slide005_core104.png'
      - 'slide006_core003.png'
      - 'slide005_core064.png'
      - 'slide005_core058.png'
      - 'slide002_core081.png'
      - 'slide002_core056.png'
      - 'slide002_core042.png'
      - 'slide006_core015.png'
      - 'slide006_core029.png'
      - 'slide003_core038.png'
      - 'slide003_core010.png'
      - 'slide001_core145.png'
      - 'slide003_core004.png'
      - 'slide005_core112.png'
      - 'slide007_core047.png'
      - 'slide002_core123.png'
      - 'slide007_core046.png'
      - 'slide003_core005.png'
      - 'slide001_core030.png'
      - 'slide001_core018.png'
      - 'slide005_core073.png'
      - 'slide002_core080.png'
      - 'slide005_core063.png'
      - 'slide002_core084.png'
      - 'slide005_core088.png'
      - 'slide006_core010.png'
      - 'slide006_core004.png'
      - 'slide001_core008.png'
      - 'slide007_core056.png'
      - 'slide005_core117.png'
      - 'slide002_core126.png'
      - 'slide007_core043.png'
      - 'slide005_core102.png'
      - 'slide007_core057.png'
      - 'slide001_core009.png'
      - 'slide006_core011.png'
      - 'slide002_core052.png'
      - 'slide005_core074.png'
      - 'slide002_core050.png'
      - 'slide006_core007.png'
      - 'slide001_core037.png'
      - 'slide007_core055.png'
      - 'slide002_core124.png'
      - 'slide005_core101.png'
      - 'slide001_core156.png'
      - 'slide006_core012.png'
      - 'slide002_core051.png'
      - 'slide002_core079.png'
      - 'slide005_core049.png'

  normalization: False
  augmentation:
    use_augmentation: True # switch everything off and on, if True automatically flips and 90 degree rotations are used in this case
    gaussian_blur_kernel: 3 # range 3-7
    brightness_limit: 0.1
    contrast_limit: 0.1
    hue_shift_limit: 10
    sat_shift_limit: 10



